language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - git clone https://github.com/fabricjs/fabric.js.git
  - npm install

script:
  - npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    target-branch: gh-pages
    local-dir: docs
